### ISSUE TITLE
IronValidatorBehavior overridden method not called

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer_elements#73]
`IronValidatorBehavior.validate` is called in JS but the Dart code of the overridden `validate` method isn't called.
https://github.com/bwu-dart-contributing/polymer_elements/blob/demo2/demo/web/iron_validatable_behavior/cats_only.dart#L25

**Comment by zoechi** [comment]
In the iron-validatable-behavior it seems to work. Investigating further ...

**Comment by zoechi** [comment]
The difference is that in the `iron-validatable-behavior` demo `validate(value)` is called directly on the Dart instance of `<cats-only>` while in the `iron-validator-behavior` demo it is called from the JS code of `IronValidatatorBehavior` https://github.com/dart-lang/polymer_elements/blob/master/lib/src/iron-validator-behavior/iron-validator-behavior.html#L57-L57

**Comment by jakemac53** [comment]
Can you try adding `@eventHandler` to that method (validate)? I think the issue is just that the method wasn't being exported to the JS element, and since its a JS behavior thats where it looks.

Seems like this would be a pretty common mistake, we probably need to do something to assist developers here, but I am not sure what that is.

**Comment by zoechi** [comment]
Yup, that works. Why, oh why, didn't I think of that myself :scream_cat:
